Iter15
vook88/go-url-shortener pull request #15
Opened 2024-03-02 07:14 UTC by vook88

2024-03-06 07:56 UTC, Bazys requested changes
1. Есть несколько вопросов.
2. Не стал дублировать вопросы про сигнатуру функций для каждого случая
3. Подключи к проекту `goimport` или даже `gofumpt` и настрой IDE на форматирование либо при каждом сохранении либо гит хук на коммит

2024-03-06 07:56 UTC, Bazys commented on internal/service/shortener.go
> +		for {
а точно надо 2 бесконечных цикла?
ведь есть default и в нем ты можешь делать что нить

2024-03-06 07:56 UTC, Bazys commented on internal/server/handlers.go
> +	log := logger.GetLogger()
ты каждый раз используешь дефолтный логер
```
// GetLogger возвращает глобальный экземпляр логгера
func GetLogger() *zerolog.Logger {
	return &log.Logger
}
```
если посмотреть в код
```
// Logger is the global logger.
var Logger = zerolog.New(os.Stderr).With().Timestamp().Logger()
```
и `func Init()` по сути висящий в воздухе код
По хорошему, логер надо инициализировать при старте приложения с нужным тебе уровнем логирвания и далее инжектировать его во все нуждающиеся структуры с помощью Dependency Injection

2024-03-06 07:56 UTC, Bazys commented on internal/server/handlers.go
>  		var dupErr *errors2.DuplicateURLError
тебе точно нужна эта переменная? может достаточно `errors.Is`

2024-03-06 07:56 UTC, Bazys commented on internal/service/shortener.go
> +func (s Shortener) BatchDeleteShortURL(ctx context.Context, shortURLs []string) {
```suggestion
func (s Shortener) BatchDeleteShortURL(_ context.Context, shortURLs []string) {
```
раз контекст не используешь, а сигнатуру функции надо соблюдать

2024-03-06 07:56 UTC, Bazys commented on internal/service/shortener.go
>  	var urls []models.BatchShortURL
размер слайса `URLs` тебе известен. преаллоцируй слайсы заранее, что бы не пересоздавать слайсы при работе аппенд.

2024-03-07 13:40 UTC, vook88 commented
> 3. Подключи к проекту `goimport` или даже `gofumpt` и настрой IDE на форматирование либо при каждом сохранении либо гит хук на коммит
Подскажи пожалуйста, что тебе не понравилось? У меня подключен goimports и при сохранении сразу все поправляет.
<img width="993" alt="image" src="https://github.com/vook88/go-url-shortener/assets/6986140/1510e4a7-9003-4c3e-9e63-b8bb24627d00">

2024-03-07 13:41 UTC, vook88 commented on internal/service/shortener.go
> +		for {
Исправил

2024-03-07 13:41 UTC, vook88 commented on internal/server/handlers.go
> +	log := logger.GetLogger()
Посмотри теперь, я правильно тебя понял?

2024-03-07 13:42 UTC, vook88 commented on internal/server/handlers.go
>  		var dupErr *errors2.DuplicateURLError
Я пытался без переменной, у меня не получилось. Я же объявил свою структуру и в ошибку закидываю URL. Не придумал как можно переписать изящнее, если подскажешь, то буду рад

2024-03-07 13:42 UTC, vook88 commented on internal/service/shortener.go
> +func (s Shortener) BatchDeleteShortURL(ctx context.Context, shortURLs []string) {
Исправил

2024-03-07 13:42 UTC, vook88 commented on internal/service/shortener.go
>  	var urls []models.BatchShortURL
Исправил

2024-03-08 11:43 UTC, Bazys commented on internal/server/handlers.go
> +	log := logger.GetLogger()
да, меня устраивает

2024-03-08 11:45 UTC, Bazys approved these changes
Проделана отличная работа!

2024-03-09 07:13 UTC, merged